SEQUENCE = "sequence"

DENSE_FLAG = "dense"
SPARSE_FLAG = "sparse"
NONE_FLAG = "none"

FPMC_MODEL = "fpmc"
RNN_MODEL = "rnn"
GRU4REC_MODEL = "gru4rec"
NARM_MODEL = "narm"
STAMP_MODEL = "stamp"
REPEATNET_MODEL = "repeatnet"
S3REC_MODEL = "s3rec"
CSRM_MODEL = "csrm"
M2TREC_MODEL = "m2trec"
SBRT_MODEL = "sbrt"
GRAPHFORMER_MODEL = "graph_former"
GNN_MODEL = "gnn"
SRGNN_MODEL = "srgnn"
GCSAN_MODEL = "gcsan"
GCEGNN_MODEL = "gce_gnn"
DHCN_MODEL = "dhcn"
NCL_MODEL = "ncl"
LESSR_MODEL = "lessr"
MSGIFSR_MODEL = "msgifsr"
FAPAT_MODEL = "fapat"

XL_FLAG = "xl"
KNN_FLAG = "knn"
